### ISSUE TITLE
respR unavailable for R version 4.0.2

### ISSUE THREAD

**Issue by speroffs** [januarharianto/respR#113]
Installation of respR package is not compatible with current R version 4.0.2 ("Taking Off Again", 6-22-2020)

**Comment by nicholascarey** [comment]
I suspect you are trying to install from CRAN or via the built-in package install options in RStudio. This won't work for respR, since it is not yet submitted to CRAN. Fortunately it's easy to install. Just a couple of lines of code. Follow the instructions here:

https://github.com/januarharianto/respR

If this is not the case, can you provide more information and context? What do you mean by "unavailable"?
