### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by louisecornwell** [januarharianto/respR#53]
When trying to install respR via GitHub, I get the following output:

> devtools::install_github("januarharianto/respR")
Downloading GitHub repo januarharianto/respR@master
from URL https://api.github.com/repos/januarharianto/respR/zipball/master
Installing respR
"//npm/pmldfs/newhome/loco/MYDOCU~1/R/R-35~1.1/bin/x64/R" --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/loco/AppData/Local/Temp/RtmpeuL1ue/devtools33c85ddc6579/januarharianto-respR-a81c111"  \
  --library="\\npm/pmldfs/Newhome/loco/My Documents/R/R-3.5.1/library"  \
  --install-tests 

'\\npm\pmldfs\newhome\loco\MYDOCU~1\R\R-35~1.1' is not recognized as an internal or external command,
operable program or batch file.
In R CMD INSTALL
Installation failed: Command failed (1)

What is it that I am doing wrong? To be clear, this works fine on my own private laptop, but I am using my work computer, so it is probably from my end not yours, but any help would be much appreciated.

**Comment by nicholascarey** [comment]
Hi Louise

This looks like a Windows error. We're both Mac users, so not much help. It could be because your work PC is not under an admin account? 

Googling "is not recognized as an internal or external command.." led to me to these which may be of some help:

https://stackoverflow.com/questions/25896508/error-when-installing-r-package-using-rstudio
https://github.com/rstudio/DT/issues/98
https://helpdeskgeek.com/how-to/fix-not-recognized-as-an-internal-or-external-command/
https://support.rstudio.com/hc/en-us/community/posts/202693946-rmarkdown-cann-t-be-installed-in-the-rstudio

Seems like the most common suggestion is that it's something to do with having a space in a filepath where RStudio is trying to install to (e.g. "C:/Program Files/"). there are some suggestions on how to fix it amongst those links. 

You could also try downloading the package as a zip file and installing it manually, but i imagine you might see the same issue. 

Cheers, Nick

**Comment by nicholascarey** [comment]
Another one - 

https://github.com/rstudio/DT/issues/98

**Comment by louisecornwell** [comment]
Hi Nick, 

Thank you so much for getting back to me. I agree this must be a windows thing, although I don't understand why it would work on my laptop (which also uses windows) but not my office computer. I have tried to follow the directions suggested in the links you sent, but I am not confident in what I am doing! I will hopefully be able to get hold of our IT guy to see if he can solve the problem. 

Will  keep you updated, 

Louise

**Comment by januarharianto** [comment]
If this isn't solved by next week I'll look into it. Sorry guys - my thesis is due for submission by Sunday (eeek).

A quick look at the error message tells me that it is also highly possible that it's a version mismatch. Is your R version lower than 3.3? Anyway sorry for this quick response!

**Comment by louisecornwell** [comment]
No problem! and no, I am using version 3.5.1. 


Good luck with your thesis :)

**Comment by louisecornwell** [comment]
Problem solved. I just needed to save my version of R in a different place. So simple!! 

Thank you for your help :)

**Comment by januarharianto** [comment]
That's great. Glad you figured out the fix! 

I'm procrastinating from my writing. Obviously...argh
